### ISSUE TITLE
Ios图片上传，旋转的问题，并未生效。。

### ISSUE THREAD

**Issue by zhangzy56** [fengshangbin/PhotoCrop#8]
这个库的旋转问题还是没有生效。

**Comment by zhangzy56** [comment]
首先感谢作者的这个库，Thanks
事实证明：
defaultPhoto: base64, // url | base64 | file
// file不支持 自动旋转 (Orientation)   base64支持

**Comment by fengshangbin** [comment]
我这边测试过几张IOS被旋转过的图，可以自动修复旋转角度。
另外 url | base64 里已经没有原始旋转数据了 不可以自动修复旋转角度（需要在把file变成url | base64的环节处理好旋转问题）
你也可以把你有问题的图片文件给我，我再做测试
